// js/flags.js — Mapping des noms CSV vers les emoji drapeaux

const FLAG_MAP = {
    "__Algerie":                          "🇩🇿",
    "__Allemagne":                        "🇩🇪",
    "__Arabie saoudite":                  "🇸🇦",
    "__Argentine":                        "🇦🇷",
    "__Australie":                        "🇦🇺",
    "__Autriche":                         "🇦🇹",
    "__Belgique":                         "🇧🇪",
    "__Benin":                            "🇧🇯",
    "__Bresil":                           "🇧🇷",
    "__Bulgarie":                         "🇧🇬",
    "__Canada":                           "🇨🇦",
    "__Chili":                            "🇨🇱",
    "__Chypre":                           "🇨🇾",
    "__Congo":                            "🇨🇬",
    "__Coree Du Sud":                     "🇰🇷",
    "__Croatie":                          "🇭🇷",
    "__Danemark":                         "🇩🇰",
    "__E.U.A.N":                          "🇺🇸",
    "__Egypte":                           "🇪🇬",
    "__Emirats Arabes Unis":              "🇦🇪",
    "__Espagne (y compris Canaries)":     "🇪🇸",
    "__Estonie":                          "🇪🇪",
    "__Etats-Unis":                       "🇺🇸",
    "__Finlande":                         "🇫🇮",
    "__Gabon":                            "🇬🇦",
    "__Ghana":                            "🇬🇭",
    "__Grèce":                            "🇬🇷",
    "__Hong-kong":                        "🇭🇰",
    "__Hongrie":                          "🇭🇺",
    "__Irlande":                          "🇮🇪",
    "__Italie":                           "🇮🇹",
    "__Japon":                            "🇯🇵",
    "__Koweit":                           "🇰🇼",
    "__Lettonie":                         "🇱🇻",
    "__Lituanie":                         "🇱🇹",
    "__Luxembourg":                       "🇱🇺",
    "__Malte":                            "🇲🇹",
    "__Maroc":                            "🇲🇦",
    "__Nouvelle-zelande":                 "🇳🇿",
    "__Oman":                             "🇴🇲",
    "__Pays-Bas":                         "🇳🇱",
    "__Philippines":                      "🇵🇭",
    "__Pologne":                          "🇵🇱",
    "__Portugal":                         "🇵🇹",
    "__Qatar":                            "🇶🇦",
    "__Republique Democratique Du Congo": "🇨🇩",
    "__Republique Populaire De Chine":    "🇨🇳",
    "__République tchèque":               "🇨🇿",
    "__Roumanie":                         "🇷🇴",
    "__Royaume-uni":                      "🇬🇧",
    "__Russie":                           "🇷🇺",
    "__Singapour":                        "🇸🇬",
    "__Slovaquie":                        "🇸🇰",
    "__Slovénie":                         "🇸🇮",
    "__Suède":                            "🇸🇪",
    "__Suisse":                           "🇨🇭",
    "__Thailande":                        "🇹🇭",
    "__Togo":                             "🇹🇬",
    "__Ukraine":                          "🇺🇦",
    "__Uruguay":                          "🇺🇾",
    "__Vietnam":                          "🇻🇳",
    "__Yemen":                            "🇾🇪",
    "_PAYS TIERS":                        "🌍",
    "_UE":                                "🇪🇺",
    "Monde":                              "🌐",
    "France":                             "🇫🇷"
};

/**
 * Retourne l'emoji drapeau correspondant au nom CSV du pays.
 * @param {string} csvName — ex: "__Allemagne", "France"
 * @returns {string} emoji drapeau ou "" si inconnu
 */
export function getFlag(csvName) {
    return FLAG_MAP[csvName] || "";
}
